#application Information

server.port=8080
server.servlet.context-path=/route-mind

spring.application.name=RouteMind

# Database Configuration
spring.datasource.url=JDBC:mysql://localhost:3306/routemind_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# FedEx API Configuration
fedex.baseUrl=https://apis-sandbox.fedex.com
fedex.apiKey=your-fedex-api-key
fedex.accountNumber=your-account-number
fedex.password=your-password
fedex.meterNumber=your-meter-number
fedex.clientId=your-client-id
fedex.clientSecret=your-client-secret
fedex.enableLogging=true
