#application Information

server:
  port: 8088
  servlet:
    context-path: /route-mind

spring:
  application:
    name: RouteMind

 # Database Configuration

  datasource:
    url: JDBC:mysql://localhost:3306/routemind_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
   
#JPA Configuration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# FedEx API Configuration
fedex:
  baseUrl: https://apis-sandbox.fedex.com  # Change to production URL when ready
  apiKey: your-fedex-api-key
  accountNumber: your-account-number
  password: your-password
  meterNumber: your-meter-number
  clientId: your-client-id
  clientSecret: your-client-secret
  enableLogging: true